# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - test
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # - name: echo the file
      #   run: |
      #     cd ${{ github.workspace }}/root-apps/${{ inputs.app-name }}
      #     sed -i 's/tag:.*$/tag: ${{ inputs.image-version }}/' values-dev.yaml

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build." >> test.yaml
          echo "test, and deploy your project." >> test.yaml

      - name: Add and commit changes (if any)
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            exit 0
          fi
          git config --global user.name 'xavierpravin'
          git config --global user.email 'xavierpravinkumar@gmail.com'
          git add .
          git commit -m "Added a file"

      - name: Push changes (consider using pull requests)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          #Pushing the code
          git push origin  HEAD:refs/heads/main --force
